name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🛠 Breaking Change'
    labels:
      - 'breaking change'
  - title: '✨ Features'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '📝 Documentation'
    label: 'documentation'
# - title: '🧰 Maintenance'
#   label: 'chore'
change-template: '- $TITLE (#$NUMBER)' #- $TITLE @$AUTHOR (#$NUMBER)
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Release Notes (DD MM YYYY)

  $CHANGES
