version: "3"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  service:
    container_name: service
    build:
      context: ./service
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
    volumes:
      - ./service/data:/app/data
    depends_on:
      - redis
