# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    setup_ci if ENV["CI"]
    update_code_signing_settings(
      use_automatic_signing: true,
      path: "../Runner.xcodeproj"
    )

    match(type: "appstore")
    build_app(skip_build_archive: true, archive_path: "../build/archive/Runner.xcarchive")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end
end
