name: Docker Image CI

on:
  push:

jobs:
  ios:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - name: Install gems
        run: bundle install
        working-directory: ./app/ios

      - name: Update signing settings
        run: bundle exec fastlane update_signing_settings
        env:
          IOS_APP_IDENTIFIER: ${{ secrets.IOS_APP_IDENTIFIER }}
          IOS_PROFILE_NAME: ${{ secrets.IOS_PROFILE_NAME }}
          IOS_TEAM_ID: ${{ secrets.IOS_TEAM_ID }}
        working-directory: ./app/ios

      - name: Get iOS certs
        run: bundle exec fastlane get_ios_certs
        env:
          IOS_APP_IDENTIFIER: ${{ secrets.IOS_APP_IDENTIFIER }} # remove in future to see if we need
          IOS_CERT_GIT_REPO: ${{ secrets.IOS_CERT_GIT_REPO }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

        working-directory: ./app/ios

      - name: Build App
        run: flutter build ipa --release

      - name: Decode App Store api key file
        uses: timheuer/base64-to-file@v1
        id: app_store_connect_api_key
        with:
          filename: "api-key.json"
          encodedString: ${{ secrets.APP_STORE_CONNECT_API_KEY }}

      - name: Update reviewer email address
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./ios/fastlane/metadata/review_information/email_address.txt
          write-mode: overwrite
          contents: ${{ secrets.REVIEWER_EMAIL_ADDRESS }}

      - name: Update reviewer first name
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./ios/fastlane/metadata/review_information/first_name.txt
          write-mode: overwrite
          contents: ${{ secrets.REVIEWER_FIRST_NAME }}

      - name: Update reviewer last name
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./ios/fastlane/metadata/review_information/last_name.txt
          write-mode: overwrite
          contents: ${{ secrets.REVIEWER_LAST_NAME }}

      - name: Update reviewer contact number
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./ios/fastlane/metadata/review_information/phone_number.txt
          write-mode: overwrite
          contents: ${{ secrets.REVIEWER_PHONE_NUMBER }}

      - name: Deploy iOS release
        run: bundle exec fastlane release
        env:
          API_KEY_PATH: ${{ steps.app_store_connect_api_key.outputs.filePath}}
        working-directory: ./app/ios
