name: Test Build Apps

on:
  push:
    branches-ignore:
      - "main"

concurrency:
  group: ${{ github.ref }}_test_build_apps
  cancel-in-progress: true

jobs:
  # android:
  #   runs-on: ubuntu-latest

  #   defaults:
  #     run:
  #       working-directory: ./app

  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: subosito/flutter-action@v2
  #       with:
  #         channel: "stable"

  #     - name: Install packages
  #       run: flutter pub get

  #     - name: Build apk
  #       run: flutter build apk

  service:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./service

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: service/package-lock.json

      - name: Install packages
        run: npm ci

      - name: Run Tests
        run: npm run build
